export enum ActionType {
    ENABLE_AUDIO = "ENABLE_AUDIO",
    LANGUAGE = "LANGUAGE",
    IS_INITIAL_SETUP = "IS_INITIAL_SETUP",
    STORE_SESSION_SIGNAL = "STORE_SESSION_SIGNAL",
    PROGRESS = "PROGRESS",
    STATS = "STATS",
}
