export enum ActionType {
    ENABLE_AUDIO = "ENABLE_AUDIO",
    LANGUAGE = "LANGUAGE",
    ROUND_STATS = "ROUND_STATS",
    IS_INITIAL_SETUP = "IS_INITIAL_SETUP",
    TIMER_STATE = "TIMER_STATE",
    CURRENT_SCORE = "CURRENT_SCORE",
}
